### ISSUE TITLE
INFROGRAFIA 

### ISSUE THREAD

**Issue by CxrlosMX** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-CxrlosMX#1]
![INFOGRAFIA LENGUAJES DE PROGRAMACION](https://user-images.githubusercontent.com/77459857/167975770-2f106c13-2a51-4ca3-9c20-6a680dcaab08.png)

**Comment by IsraelNicolas61** [comment]
20/20 Buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado
